### PR TITLE
chore: install lerna and move packages to packages folder

### PR DESCRIPTION
**Pull request by benoitdeziel**
## Description

This PR moves all the packages to the `packages` folder and install `lerna`

## Checklist

- [ ] ~Updated the version number in the `package.json`~
- [ ] ~Test any new configuration on a repo using [`npm link`](https://docs.npmjs.com/cli/link)~

### CODE REVIEW

**Review by hjack-landr — APPROVED** [review]
nice, LGTM! now that we have `CHANGELOG` files, maybe we should add a checklist item to the PR template as a reminder to up date them?

**Comment by benoitdeziel** [comment]
@hjack-landr the `CHANGELOG.MD` will be updated automatically based on the PR, something like [this](https://github.com/intuit/auto/blob/master/CHANGELOG.md)

**Comment by hjack-landr** [comment]
@benoitdeziel fantastic 👍

**Comment by benoitdeziel** [comment]
:rocket: PR was released in [`eslint-config-landr@0.5.0`](https://github.com/LandrAudio/linting-and-formatting/releases/tag/eslint-config-landr%400.5.0), [`prettier-config-landr@0.2.0`](https://github.com/LandrAudio/linting-and-formatting/releases/tag/prettier-config-landr%400.2.0), [`stylelint-config-landr@0.1.0`](https://github.com/LandrAudio/linting-and-formatting/releases/tag/stylelint-config-landr%400.1.0) :rocket:

**Pull request merged**
